# POST http://localhost:5000/api/auth/register HTTP/2.1
# content-type: application/json

# {
#     "mobile": "09198881400",
#     "password": "09198881400",
#     "repassword": "09198881400"
# }

# POST http://localhost:5000/api/auth/login HTTP/2.1
# content-type: application/json

# {
#     "mobile": "09198881400",
#     "password": "09198881400",
#     "repassword": "09198881400"
# }

# PUT http://localhost:5000/api/auth/update/635141f38f13060fbbdddb55 HTTP/2.1
# content-type: application/json

# {
#     "mobile": "09198881400",
#     "password": "09198881400",
#     "repassword": "09198881400"
# }


# DELETE http://localhost:5000/api/auth/delete/6351398e8f13060fbbdddb4e HTTP/2.1
# content-type: application/json






# # Get All Cv
# GET http://localhost:5000/api/cv/63526a5e33463d8190181129 HTTP/2.1
# content-type: application/json


# GET http://localhost:5000/api/cv/63526a5e33463d8190181129/63526a5e33463d819018112b HTTP/2.1
# content-type: application/json


POST http://localhost:5000/api/cv/63526a5e33463d8190181129/63526a5e33463d819018112b HTTP/2.1
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiJ9.MDkxOTg4ODE0MDA.Y0Ct6fFaiflF0qwifr_tU90lUZJL0CYqQN4krYuXc4U
{
  "_id": "635141f38f13060fbbdddb57",
  "userId": "635141f38f13060fbbdddb55",
  "theme": {
    "color": "red",
    "font": "calibri",
    "lang": "en"
  },
  "image": "https://static.farakav.com/files/newspapers/varzesh3/820_Esteghlal-1400-01-19_1617824656.jpg?w=870",
  "about": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat",
  "title": "title",
  "subTitle": "subTitle",
  "fullName": {
    "first": "amir",
    "last": "maghami"
  },
  "address": {
    "country": "iren",
    "province": "azerbajan",
    "region": "khoy"
  },
  "skillsSummary": [
    {
      "label": "web"
    }
  ],
  "contacts": [
    {
      "label": "web",
      "icon": "cib:linkedin"
    }
  ],
  "educations": [
    {
      "label": "it"
    }
  ],
  "techExperiences": [
    {
      "label": "html"
    }
  ],
  "softwareKnowledges": [
    {
      "label": "basic",
      "skills": [
        {
          "label": "html"
        }
      ]
    }
  ],
  "experiences": [
    {
      "title": "front end developer",
      "company": {
        "name": "haco",
        "url": "haco.ir"
      },
      "description": "lorem",
      "beginDate": "234243",
      "endDate": "234243",
      "skills": [
        {
          "label": "html"
        }
      ]
    }
  ],
  "socials": [
    {
      "label": "instagram",
      "icon": "cib:linkedin",
      "link": "instagram.ir"
    }
  ],
  "__v": 0
}



# PUT  http://localhost:5000/api/cv/cv/63526a5e33463d8190181129/63526a5e33463d819018112b HTTP/2.1
# content-type: application/json
# x-auth-token: eyJhbGciOiJIUzI1NiJ9.MDkxOTg4ODE0MDA.Y0Ct6fFaiflF0qwifr_tU90lUZJL0CYqQN4krYuXc4U
# {
#   "_id": "635141f38f13060fbbdddb57",
#   "userId": "635141f38f13060fbbdddb55",
#   "theme": {
#     "color": "red",
#     "font": "calibri",
#     "lang": "en"
#   },
#   "image": "https://static.farakav.com/files/newspapers/varzesh3/820_Esteghlal-1400-01-19_1617824656.jpg?w=870",
#   "about": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat",
#   "title": "title",
#   "subTitle": "subTitle",
#   "fullName": {
#     "first": "amir",
#     "last": "maghami"
#   },
#   "address": {
#     "country": "iren",
#     "province": "azerbajan",
#     "region": "khoy"
#   },
#   "skillsSummary": [
#     {
#       "label": "web"
#     }
#   ],
#   "contacts": [
#     {
#       "label": "web",
#       "icon": "cib:linkedin"
#     }
#   ],
#   "educations": [
#     {
#       "label": "it"
#     }
#   ],
#   "techExperiences": [
#     {
#       "label": "html"
#     }
#   ],
#   "softwareKnowledges": [
#     {
#       "label": "basic",
#       "skills": [
#         {
#           "label": "html"
#         }
#       ]
#     }
#   ],
#   "experiences": [
#     {
#       "title": "front end developer",
#       "company": {
#         "name": "haco",
#         "url": "haco.ir"
#       },
#       "description": "lorem",
#       "beginDate": "234243",
#       "endDate": "234243",
#       "skills": [
#         {
#           "label": "html"
#         }
#       ]
#     }
#   ],
#   "socials": [
#     {
#       "label": "instagram",
#       "icon": "cib:linkedin",
#       "link": "instagram.ir"
#     }
#   ],
#   "__v": 0
# }